### PR TITLE
Implement SwapOut support

### PR DESCRIPTION
**Pull request by jmrossy**
Fixes https://github.com/mento-protocol/mento-web/issues/56

- Refactor swap hooks and forms to be bidirectional
- Implement swapOut transactions
- Update alfajores + baklava exchange addresses
- Write unit tests for swap utilities
- Normalize import paths
- Tweak form colors
- Fix footer links

### CODE REVIEW

**Review by philbow61 — CHANGES_REQUESTED** [review]
LGTM 👍 

but I noticed one thing when checking out the preview:
1. It seems like the price is not displayed correctly in this direction
image

And I do think we have a decimal conversion error.
image

**Comment by jmrossy** [comment]
> And I do think we have a decimal conversion error.

Thanks for the review! I think the problem is with inconsistent decimal values for the axlUSDC tokens on different chains. I'll get it sorted

**Comment by jmrossy** [comment]
@philbow61 Fixed! It was stale addresses for usdc on alfajores/baklava and a typo in useSwapQuote 🤦‍♂️

**Comment by bayological** [comment]
> @philbow61 Fixed! It was stale addresses for usdc on alfajores/baklava and a typo in useSwapQuote man_facepalming
> 
> Note, USDC swaps will still only work on Mainnet because the pools haven't been properly prepared on testnets yet. They return this error even for small swap: `Exceeding the amount reserve holds`

This still seems to be an issue @jmrossy

**Comment by jmrossy** [comment]
@bayological Are you maybe looking at an outdated preview build or something? I seems to work well for me:
Screenshot 2023-07-05 at 10 17 44 AM

**Review by bayological — APPROVED** [review]
@jmrossy This looks good to me. Nice work. 

When I was testing the updates, I found another [issue](https://github.com/mento-protocol/mento-web/issues/76). This seems to be the result of a previous change as it's also an issue in prod.

**Review by philbow61 — APPROVED** [review]
Nice work 🥇

**Review by ninocomputer — APPROVED** [review]

**Pull request merged**
