### PR TITLE
feat: add native USDC to Baklava

### PR DESCRIPTION
**Pull request by nvtaveras**
### Description

This adds the native USDC pools to Baklava after we recently executed MU06. Baklava uses a mock 6 decimals token but Alfajores will use the actual USDC token deployed by Circle once we execute the proposal there prior to mainnet.

### Other changes

Some other small changes to rename bridged tokens to `axlXXX`

### Tested

Ran it locally and did swaps on all directions

### Related issues

https://github.com/mento-protocol/mento-web/issues/119

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] The PR title follows the [conventions](https://www.notion.so/Git-Branching-and-Commit-Message-Conventions-18f66f7d06444cfcbac5725ffbc7c04a?pvs=4#9355048863c549ef92fe210a8a1298aa)
- [ ] I have run the [regression tests](https://www.notion.so/Mento-Web-App-Regression-Tests-37bd43a7da8d4e38b65993320a33d557)

### CODE REVIEW

**Review by denviljclarke — APPROVED** [review]
LGTM

**Review by denviljclarke — APPROVED** [review]

**Review by bayological — CHANGES_REQUESTED** [review]
I'm able to swap into USDC but swapping out does not work. Looks like a decimal issue.
image

**Comment by nvtaveras** [comment]
@bayological Are you doing max in that trade? If so, it's an existing issue not introduced by this PR. You should be able to trade an amount that's near the max

**Comment by bayological** [comment]
> @bayological Are you doing max in that trade? If so, it's an existing issue not introduced by this PR. You should be able to trade an amount that's near the max

I was doing the max and confirmed this is an existing issue.

**Review by bayological — APPROVED** [review]

**Pull request merged**
