### PR TITLE
feat: persist asset selection

### PR DESCRIPTION
**Pull request by gabrieltemtsen**
### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

Added a "confirmView" to the redux state, so we can persist the formValues when a user clicks on the back button during a swap.

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #issue number here
#90 

### Checklist before requesting a review

- [ -] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] The PR title follows the [conventions](https://www.notion.so/Git-Branching-and-Commit-Message-Conventions-18f66f7d06444cfcbac5725ffbc7c04a?pvs=4#9355048863c549ef92fe210a8a1298aa)
- [ ] I have run the [regression tests](https://www.notion.so/Mento-Web-App-Regression-Tests-37bd43a7da8d4e38b65993320a33d557)

### CODE REVIEW

**Comment by gabrieltemtsen** [comment]
Hi @bayological  any word?

**Comment by bayological** [comment]
@gabrieltemtsen LGTM, let's get the branch updated and the checks passing

**Comment by gabrieltemtsen** [comment]
Alright

**Comment by gabrieltemtsen** [comment]
Hi @bayological the build error from the action is due to this ( unhandledRejection Error: No projectId found.) 
if the repo could have the new Wallet Connect (now Reon) project ID --- it will pass.

**Comment by bayological** [comment]
> Hi @bayological the build error from the action is due to this ( unhandledRejection Error: No projectId found.) if the repo could have the new Wallet Connect (now Reon) project ID --- it will pass.

Np, secrets are only passed to the runner for PRs from collaborators. Will merge and close this. Thanks again 🙏

**Review by bayological — APPROVED** [review]

**Pull request merged**
